- package-lock.json
- package.json
- src/index.css
- tailwind.config.js
Related #6
- recoil 설치
- design system 피그마보고 custom color (scale제외) palette 생성 (tailwind.config.js)
- input과 select에 적용할 custom class 생성하여 (index.css)
- 텍스트 컬러와 폰트(standard)는 전체 적용 (index.css)
- 제 파트만 그런지 모르겠는데 input이랑 select가 기본 스타일이 똑같아서 input-select 이름으로 custome class 만들어 index.css에 넣었습니다.
round, padding, border, outline만 넣었고 width는 각자 추가하면 되지 않을까 합니다. 의견있으시면 말씀주세요!
> 6 recoil 설치 및 tailwind css custom templete 생성

- src/index.css
- index.css에서 body에 mx-6 적용
- mx-6가 적당한지 각자 페이지에서 적용 및 확인
> body 양쪽 margin 적용

- .eslintrc.json
- package-lock.json
- src/App.tsx
- src/atoms/commonAtom.ts
- src/components/common/inputContact.tsx
- src/components/common/inputMemo.tsx
- src/components/common/inputName.tsx
- src/components/common/selectDate.tsx
- src/components/common/selectInstructor.tsx
- src/components/common/selectTime.tsx
- commonAtom.ts 생성
- inputContact.tsx
- inputMemo.tsx
- inputName.tsx
- selectDate.tsx
- selectInstructor.tsx
- selectTime.tsx
- eslint 수정
- App.tsx에 공통 컴포넌트 삽입
- 컴포넌트명이나 파일명 수정 필요 시 말해주세요
> 14 common components 생성 (Mark up+Styling+일부 기능 구현) + eslint 수정

- .eslintrc.json
- src/App.tsx
- src/atoms/commonAtom.ts
- src/components/common/inputContact.tsx
- src/components/common/inputMemo.tsx
- src/components/common/inputName.tsx
- src/components/common/selectDate.tsx
- src/components/common/selectInstructor.tsx
- src/components/common/selectTime.tsx
- 공통 컴포넌트의 title 부분들 props로 받아오도록 수정
- eslint ignorePatterns에 "tailwind.config.js" 추가
- eslint "react/prop-types": "off" 추가
> 19 common components 수정 (title을 props로 받아오기) + eslint 수정

- src/routes/checkSchedule.tsx
- 일정상세-조회 마크업과 스타일링 적용
- 임시로 mock 데이터를 생성해 fetch
> 8 check schedule 마크업, 스타일링

- package-lock.json
- package.json
- src/App.tsx
> 24 react router dom

- src/index.css
related #26
- main title custom class 추가
- small title custom class 추가
- title 이름 main, small로 구분했는데 괜찮은가요? 변경 필요하면 말씀주세요
- 글씨 진하게랑 사이즈, 마진 정도만 넣어놨는데 추후에 다같이 보면서 스타일 수정 및 추가하면 될 듯합니다
> 26 Title custom class 추가

- package-lock.json
- package.json
- src/main.tsx
- React Query 프로덕션 의존성으로 설치 완료
- routes 폴더 안, login.tsx 생성 완료
- 27(화) 저녁 package 관련 이슈들이 해결되지 않은 상황, 해결 이후 React Query에 문제가 없는지 확인 필요
> 29 2 react query for login

- src/index.css
- tailwind CSS 커스텀 스타일 변경
- PC breakpoints 설정 : 폰트사이즈, margin 수정
- basic-font 추가 : 기본 폰트사이즈 설정 값
> Style: tailwind 스타일 breakpoints에 맞춰 변경

- package-lock.json
- package.json
> 38 Modal 설치

- public/data/scheduleData.json
- src/components/common/Card.tsx
- src/index.css
- src/routes/checkSchedule.tsx
- Card 컴포넌트 분리
- tailwind CSS 커스텀 스타일에 맞춰 class 속성 변경
- ScheduleItemData 타입 정의
> 23 check schedule

- public/data/counselingData.json
- src/App.tsx
- src/atoms/checkCounselingAtom.ts
- src/atoms/counselingAtom.ts
- src/components/counseling/CounselingModal.tsx
- src/routes/counseling/checkCounseling.tsx
- src/routes/counseling/createCounseling.tsx
related #34 
- 상담 조회 페이지 Mark up
- 상담 조회 페이지 Styling (Tailwind CSS)
- mock data 생성 및 호출
- 상담 기록 버튼 클릭시 내용 입력할 모달창 뜨기, 내용 저장
> 34 일정관리-상담-일정 상세조회 페이지 Markup+Styling+Mocking+Modal

- public/data/scheduleData.json
- src/routes/checkSchedule.tsx
- src/utils/date.ts
- 출결 이벤트 핸들링에 필요한 함수생성 및 적용
- 날짜, 시간 출력함수 utils에 만들어 적용
- api 통신 fetch -> axios 방법으로 변경
> 43 check schedule handler

- package-lock.json
- package.json
- src/utils/apiInstance.ts
- tsconfig.json
- axios 인스턴스 생성
- baseURL은 env 환경변수로 설정
> axios 인스턴스 생성

- src/components/common/InputContact.tsx
- src/components/common/InputMemo.tsx
- src/components/common/InputName.tsx
- src/components/common/SelectDate.tsx
- src/components/common/SelectInstructor.tsx
- src/components/common/SelectTime.tsx
components/common에 삭제된 파일 복원
- InputContact.tsx
- InputMemo.tsx
- InputName.tsx
- SelectDate.tsx
- SelectInstructor.tsx
- SelectTime.tsx
-
> restore: 삭제된 파일 복원

- src/components/ScheduleBox.tsx
- src/components/ScheduleDetail.tsx
- src/components/common/Header.tsx
- src/routes/checkSchedule.tsx
- src/types/schedule.ts
- Header 공통 컴포넌트 생성
- 일정조회 페이지 컴포넌트 분리 및 생성
> 49 change schedule

- src/App.tsx
- src/routes/login.tsx
- src/routes/main.tsx
- 28일 로그인 기능 마무리
- 메인 페이지 작업
- 멘토님 모킹 예시 코드
- PC (맥 -> 윈도우) 이동으로 인한 급한 commit
> 37 로그인 페이지 스타일링 기능

- .eslintrc.json
- src/atoms/itemDataAtom.ts
- src/components/ScheduleBox.tsx
- src/components/common/NameTag.tsx
- src/components/common/SelectInstructor.tsx
- src/routes/changeSchedule.tsx
- src/routes/checkSchedule.tsx
- src/utils/date.ts
- itemDataAtom을 생성하여 리코일로 개인수업 데이터 관리하여 가져오도록 함
- 개별적으로 필요한 NameTag 컴포넌트 따로 분리 작업
- date 유틸함수 형식에 맞게 수정
> changeSchedule recoil로 데이터 가져오기

- src/App.tsx
- src/main.tsx
- src/routes/login.tsx
- src/routes/main.tsx
- 메인 페이지 모킹 예시 코드 에서의 에러 및 문제점 해결
- 로그인 기능 마무리 중 로그인 정보 제출 이후 메인 페이지로 이동 되지 않는 문제 해결
- 리코일을 통한 accessToken 의 전역 상태 관리.
- App.tsx 에 BrowserRouter 를 감싸고 있던 RecoilRoot 코드를 main.tsx 로 뺐음.
- 리코일 코드 수정으로 인한 오류 발생 여부 확인 필요
- accessToken을 전역 상태 관리 함으로, 이것을 활용한 코드 개선이 가능할 것으로 예상.
> 62 main_작업중

- src/App.tsx
- src/index.css
- src/routes/ticket/centerTicket.tsx
- src/routes/ticket/createTicket.tsx
- 수강권 조회, 생성 페이지 라우터 적용
- 마크업 및 스타일링
- 임시 데이터 생성 및 api 연동 테스트 진행
> center ticket 수강권 조회 페이지 생성

- public/data/membersData.json
- src/App.tsx
- src/atoms/members/membersAtom.ts
- src/components/common/InputBirth.tsx
- src/components/common/SelectJob.tsx
- src/components/common/SelectSex.tsx
- src/components/common/SelectVisitRoute.tsx
- src/components/members/AgreeCondition.tsx
- src/routes/counseling/checkCounseling.tsx
- src/routes/counseling/createCounseling.tsx
- src/routes/members/createMembers.tsx
- src/routes/members/showMembers.tsx
- src/types/counselingSchedule.ts
- src/types/members.ts
- 상담 일정 관리 오류 해결
- 회원 관리 메인 페이지 (showMembers) 생성
- 회원 생성 페이지 (createMembers) 생성
- 공통 컴포넌트 (성별, 생년월일, 방문경로, 직업 선택) 생성
close #68
> 68 회원관리 메인/회원생성 페이지 생성

- src/components/common/InputBirth.tsx
- src/components/common/SelectSex.tsx
- src/routes/members/showMembers.tsx
- src/types/members/members.ts
- 회원 생성 시 성별, 날짜 부분 입력 값 수정
- 입력 값 수정 이후 계속 404 DataIntegrityViolationException 에러가 남.. 원인 및 해결 방법 논의 필요
> 77 회원 생성 시 성별, 날짜 부분 입력 값 수정

- src/components/centerTicket/Input.tsx
- src/components/centerTicket/Select.tsx
- src/index.css
- src/routes/ticket/centerTicket.tsx
- src/routes/ticket/createTicket.tsx
- Select, Input 공통 컴포넌트를 이용한 수강권 추가 페이지 스타일링 진행
> 75 center ticket 수강권 추가 페이지 스타일링

- src/routes/main.tsx
- src/utils/apiInstance.ts
- 작업 중 토큰 갱신이 제대로 이뤄지지 않는 것으로 보여 해결중
> fix : 토큰 만료전 갱신 기능 오류 발견, 해결중

- package-lock.json
- package.json
- src/App.tsx
- src/components/common/BottomNav.tsx
- src/routes/schedule.tsx
- src/toastUI.d.ts
- toatUI 설치 및 세팅, 테스트
- 서버에서 일정을 받아 그리는 기능 추가 필요
- 월간 화면에서 주간, 일간 화면으로 이동하는 기능 필요.
> feat : toastUI calendar 설치 및 세팅, 테스트

- src/routes/schedule.tsx
> style : 공통 layout 적용

- src/routes/members/showMembers.tsx
> Fix: div태그 빠진거 수정

- src/components/layout/Layout.tsx
- src/routes/schedule/changeSchedule.tsx
> 기타 수정사항 fix

- src/routes/scheduleApi.tsx
> Chore: 개인 수업 일정 생성 버튼 연결

- src/routes/counseling/checkCounseling.tsx
- src/routes/scheduleApi.tsx
> Fix: 임시 상담 일정 상세 조회 페이지 추가

- src/atoms/user/userAtom.ts
- src/components/common/SubHeader.tsx
- src/components/layout/MainHeader.tsx
- Recoil 
- 로그인한 사용자정보를 담을 userState atom 생성하여 메인헤더에 적용
> userState atom 생성 및 메인헤더 적용

- src/atoms/counseling/counselingScheduleAtom.ts
- src/routes/counseling/createCounseling.tsx
- src/routes/scheduleApi.tsx
- 일정 조회 페이지에서 상담 일정 조회 안되는 부분 수정
- 상담 일정 생성 상세 기능 추가 중
> Fix: 일정 조회 페이지에서 상담 일정 조회 안되는 부분 수정, 상담 일정 생성 상세 기능 추가 중

- src/components/layout/BottomNav.tsx
- src/routes/schedule.tsx
- src/routes/scheduleApi.tsx
- src/utils/scheduleUtils.ts
- scheduleUtils.ts 생성, 일정 데이터 분류 및 tui.calendar 와 api 데이터 매칭
- schedule 페이지에서 scheduleUtils.ts 를 통해 가공된 데이터를 그리는 로직 구현 중
- api를 통해 서버에서 받은 데이터와 ui에서 그려지는 데이터가 매칭이 안되고 있음.
- scheduleUtils.ts 안의 객체 키 값에 대한 정리 필요
> 100 calendar/ scheduleUtils.ts 생성 및 렌더링 로직 변경 [작업중]

- src/App.tsx
- src/components/layout/BottomNav.tsx
- src/components/layout/Layout.tsx
- src/components/layout/MainHeader.tsx
- src/routes/myPage.tsx
- 이슈 생성 전 마이 페이지 작업 테스트
- 공통 Layout 수정
- bottomNav 경로 수정
- 헤더 nav 바 항목 다르게 보이게 수정
- App.tsx 에 route 추가
- 기타 등등...
> feat : 마이페이지 작업 시작(공통 Layout 수정 및 페이지 기초 작업 중)

- src/App.tsx
- src/atoms/token/accessTokenAtom.ts
- src/routes/auth/LoginRouter.tsx
- 로그인 여부에 따른 route 컴포넌트 생성 및 적용
- 토큰이 없을때 페이지 접근시 로그인하도록 구현함
close #131
> Feat: 로그인 여부에 따른 route 컴포넌트 생성 및 적용

- src/App.tsx
- src/components/common/SearchBox.tsx
- src/components/common/SearchResults.tsx
- src/routes/home.tsx
- src/types/search/search.ts
- [feat : 통합 검색 컴포넌트 생성 및 home.tsx 탑재](https://github.com/pie-sfac/1-16-careMango/commit/093b771bf2ed9ee30e935bb07ed5e16ed40411b7)
- App.tsx 에 검색 결과 페이지 라우터 탑재
- type에 검색에 필요한 타입을 설정
-
> feat : 통합 검색 컴포넌트 생성 및 home.tsx 탑재

- src/App.tsx
- src/components/layout/BottomNav.tsx
- src/components/layout/MainHeader.tsx
- src/routes/auth/LoginRouter.tsx
- Home 컴포넌트 경로 '/'로 변경
- recoil 사용하여 로그인/로그아웃에 따른 메인헤더 사용자 정보 fetch
close #131
> 홈 경로 변경 및 메인헤더 수정

- src/components/common/Input/Input.tsx
- src/index.css
- src/routes/tickets/centerTicket/createTicket.tsx
- 센터수강권 생성화면에서의 유효성 검사
- input 입력에 음수값 막기
- input type이 number일때 생기는 화살표 제거하기
- input 글자수 제한
- 입력값에 대한 required 속성 추가
> 137 ticket validation

- src/components/common/CompleteButton.tsx
- src/routes/tickets/centerTicket/createTicket.tsx
- src/types/tickets/tickets.ts
- src/utils/button.ts
- allFieldsCompleted 유틸함수 추가
- CompleteButton 공통 컴포넌트 생성
close #141
> 입력값 필드를 확인하는 CompleteButton 공통 컴포넌트 생성

- src/routes/login.tsx
- 로그인 페이지 관리자, 직원 구분 로그인 로직 에러 해결
-
> fix : 관리자, 직원 로그인 구분 기능 에러 해결

- src/components/layout/MainHeader.tsx
- 공통 레이아웃 메인 헤더 프로필 사진 클릭 시 로그아웃 버튼 나오게끔 구현
- 로컬 스토리지를 비우고 새로고침 하게끔 기능 구현
- 추가 스타일링 필요
> 152 log out

- src/pages/home/components/Cards.tsx
- src/pages/home/components/InfoCard .tsx
- src/pages/home/home.tsx
- src/pages/schedule/components/EventTable.tsx
- src/pages/schedule/components/Legend.tsx
- src/pages/schedule/components/Statistics.tsx
- src/pages/schedule/components/SubHeader.tsx
- src/pages/schedule/schedule.tsx
- src/types/home/cardConfig.ts
- [메인 페이지 기능 추가(card 를 클릭할 시 해당 정보 관리 페이지로 이동)](https://github.com/pie-sfac/1-16-careMango/pull/166/commits/bdad49928380f0251681a2fd7c26eda19f571d17)
- [상단에서 날짜 선택시 해당 날짜에 맞는 달력 페이지를 보여지게끔…](https://github.com/pie-sfac/1-16-careMango/pull/166/commits/0e985d82f3b29d8716ac2c821e4c692328c99d22) 
0e985d8
… 하는 기능
- 임시로 넣어둔 날짜 값 선택 된 날짜 값으로 나오게끔 기능 추가
- schedule.tsx 페이지 컴포넌트화
-
> 160 enhancement componentize #161

- src/atoms/counseling/counselingScheduleAtom.ts
- src/pages/counseling/components/CounselingScheduleDetail.tsx
- src/pages/counseling/createCounseling.tsx
- src/pages/scheduleApi.tsx
- validation
- 기존의 일정과 시간을 겹쳐서 생성 시 "선택하신 시간대와 겹치는 일정이 있습니다. 시간을 다시 설정해 주세요." 문구 alert
- 상담 일정 상세 조회에서 상담 기록 api 연동 (get 기존 기록, put 새 기록)
closed #165
> 일정관리-상담 validation 처리, 상담 기록 api 연동

- src/pages/privateLesson/components/ButtonAddPeople.tsx
- src/pages/privateLesson/components/PeopleListItem.tsx
- src/pages/privateLesson/createPrivateLesson.tsx
- createCounseling 및 createTicekt 코드 참고
- <Select /> 에 하드코딩하여 일정 생성 
- 스타일 및 하드 코딩 부분 수정 필요
- 일정 생성 후 화면 이동 등 수정 필요
> feat: 개인수업 일정 생성. 하드코딩

- src/App.tsx
- src/pages/tickets/centerTicket/createTicket.tsx
- src/pages/tickets/centerTicket/getTicketDetail.tsx
- src/pages/tickets/centerTicket/updateTicket.tsx
- src/pages/tickets/components/DetailDropdown.tsx
- 센터 수강권 상세 페이지 dropdown 구현
- 편집 기능
- 판매종료/판매가능 기능
- 수강권 삭제 기능
- getTicketDetail, DetailDropDown, updateTicket, createTicket 리액트 쿼리 적용
> 센터 수강권 상세 기능추가 및 리액트쿼리 적용

- src/App.tsx
- src/pages/counseling/components/SelectStaffs.tsx
- src/pages/counseling/getStaffsList.tsx
- src/pages/tickets/centerTicket/getTicketList.tsx
- src/pages/tickets/components/TicketList.tsx
- src/pages/tickets/issuedTicket/createIssuedTicket.tsx
- 센터수강권 조회 화면 판매중, 판매종료 탭을 이용한 수강권 filtering
- 수강권 부여에서 담당강사 불러오기
> 티켓 상세 filtering tab, SelectStaffs 적용

- src/App.tsx
- src/pages/staffs/components/StaffListItem.tsx
- src/pages/staffs/getStaffDetail.tsx
- 직원 상세 정보 화면 마크업
- 직원 상세 조회 API 연결 완료
- 각 버튼 기능 및 스타일 개선 필요
> 178 staff detail

- src/App.tsx
- src/pages/staffs/getStaffDetail.tsx
- src/pages/staffs/getStaffs.tsx
- src/pages/staffs/updateStaffInfo.tsx
- 직원 퇴사 기능
- 피그마 상으로는 퇴사 처리 시 직원 정보만 조회 가능하다고 하나 직원 조회 API로 불러오는 경우 보이지 않음
> 185 staff update

- src/components/layout/MainHeader.tsx
- src/pages/myPage.tsx
- src/pages/schedule/components/EventTable.tsx
- src/pages/schedule/components/ScheduleHeader.tsx
- src/pages/schedule/components/Statistics.tsx
- src/pages/schedule/schedule.tsx
- src/utils/scheduleUtils.ts
- aside 에서 일정을 클릭할 시 해당 일정의 관리 (수정) 페이지로 이동 하게 하는 기능 구현
- [취소율 부분 임시로 넣어뒀던 값 실제 값으로 교체](https://github.com/pie-sfac/1-16-careMango/pull/193/commits/7b7433444073efc5c7f6f8bb48a098e92daf5a85)
- [api 상 제공 안된 기능 및 구현 불가 부분들 주석 처리 등 정리](https://github.com/pie-sfac/1-16-careMango/pull/193/commits/3b1d49058c397be6318876e8bcd980c8e5c7fd25)
-
> 186 calendar enhancement

- src/components/common/CompleteButton.tsx
- src/components/common/Select/Select.tsx
- src/pages/schedule/components/ScheduleBox.tsx
- src/pages/schedule/components/ScheduleDetail.tsx
- src/pages/schedule/components/ScheduleUpdateForm.tsx
- src/pages/schedule/getScheduleDetail.tsx
- src/pages/schedule/updateSchedule.tsx
- src/types/schedule/schedule.ts
- 일정변경 api 오류 해결
- 일정조회, 변경, 출결, 취소 react-query 사용으로 변경하여 비동기 데이터 관리
- 불필요한 코드 제거
> 개인일정 변경 api 오류 해결 및 react-query 적용

- src/components/layout/Layout.tsx
- src/components/layout/MainHeader.tsx
- 메인헤더만 있도록 변경 
- 메뉴 구현, 센터관리 서브메뉴 생성
> Fix: 메인헤더 메뉴, 레이아웃 변경

- src/pages/tickets/centerTicket/createTicket.tsx
- src/pages/tickets/centerTicket/getIssuedList.tsx
- src/pages/tickets/centerTicket/getTicketDetail.tsx
- src/pages/tickets/centerTicket/getTicketList.tsx
- src/pages/tickets/components/IssuedTicketItem.tsx
- src/pages/tickets/components/TicketList.tsx
- src/pages/tickets/issuedTicket/createIssuedTicket.tsx
- src/pages/tickets/issuedTicket/getIssuedTicket.tsx
- src/pages/tickets/issuedTicket/getIssuedTicketDetail.tsx
- 수강권에 react-query를 적용하여 비동기 데이터 관리하기
- 코드 리팩토링
> 리액트 쿼리 적용 및 리팩토링

- src/pages/tickets/centerTicket/updateTicket.tsx
- src/pages/tickets/issuedTicket/createIssuedTicket.tsx
- 회원에게 수강권 부여한 후 회원 수강권리스트 페이지로 경로 이동
close #212
> 수강권 부여 후 경로 오류 해결

- src/App.tsx
- src/pages/counseling/components/CounselingScheduleDetail.tsx
- src/pages/counseling/createCounseling.tsx
- src/pages/counseling/getCounselingDetail.tsx
- src/pages/counseling/updateCounseling.tsx
- src/pages/schedule/components/EventTable.tsx
> Fix: schedule 경로 오류 수정

- src/pages/schedule/components/EventTable.tsx
- src/utils/scheduleUtils.ts
- [fix : 개인수업 출석, 결석, 예약 여부에 따른 표시 문제 해결](https://github.com/pie-sfac/1-16-careMango/commit/e5d16699cbdc886ead278aebcb7a675464a54476)
-
> fix : 개인수업 출석, 결석, 예약 여부에 따른 표시 문제 해결

- src/pages/counseling/getCounselingDetail.tsx
> 일정 취소 시 일정 관리 메인 페이지로 이동

- src/utils/scheduleUtils.ts
- [fix : schedule 우측 일정 title 부분 개인 수업일 경우 강사 이름이 나오는 것을 회원 이름으로 변경, 취소된 일정의 경우 보이지 않게끔 수정](https://github.com/pie-sfac/1-16-careMango/commit/70057276177578968733579dbb53310dedb02b50) 
-
> 194 schedule aside

- src/pages/counseling/updateCounseling.tsx
> 일정 변경 후 경로 수정

- src/pages/counseling/components/CounselingScheduleDetail.tsx
> 상담 기록 경로 수정

- README.md
- src/pages/schedule/schedule.tsx
- src/utils/scheduleUtils.ts
- [docs : 로그인/스케쥴/마이페이지 기능 문서화](https://github.com/pie-sfac/1-16-careMango/commit/9c0c746c33c40ba0099a27f22c453fe02f03f45a)
-
> 214 function log Closes #214

- README.md
> readme 내용 수정
